FROM golang:1.22.1-alpine3.19 AS build-perushttpd
WORKDIR /app
RUN apk add --no-cache git
RUN git clone https://github.com/shamrin/perushttpd .
RUN go mod download
RUN go build -o perushttpd .

FROM alpine:3.19
COPY index.html /app/dist/index.html
COPY --from=build-perushttpd /app/perushttpd /app/perushttpd
CMD /app/perushttpd -d /app/dist

# TODO: s6-overlay tailscale instructions